version: '3.7'

services:
  mysql_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASS
      MYSQL_DATABASE: DB_NAME
      MYSQL_PASSWORD: DB_NAME
    ports:
      - 3306:3306
    # everything inside ./scripts will me copied  to docker-entrypoint-initdb.d
    # scripts and sql files are execute as soon as the database engine is install withing the container
    # volumes:
      # - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - my-net

  redis:
    restart: always
    image: redis:5
    container_name: my-redis
    ports:
      - '6379:6379'
    networks:
      - my-net

networks:
  my-net:
    driver: bridge